version: "3.5"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
    
      NODE_OPTIONS: "--openssl-legacy-provider"

networks:
  app-network:
